random-filter-s:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [{"nprobe": 1},
              {"nprobe":2},
              {"nprobe":4}]    
random-s:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF1024,SQ8"}]
          query-args: |
            [{"nprobe": 1},
              {"nprobe":2},
              {"nprobe":4}]
yfcc-10M-unfiltered:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", "binarysig": true, "threads": 16}]
          query-args: |
            [{"nprobe": 1}, {"nprobe": 4}, {"nprobe": 16}, {"nprobe": 64}]
yfcc-10M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 8
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]
wiki-10M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 8
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

wiki-1M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

wiki-20M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

wiki-30M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

wiki-35M:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

audio:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

crawl:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

enron:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

gist:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

uqv:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

msong:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF16384,SQ8", 
              "binarysig": true, 
              "threads": 16
            },
            {"indexkey": "IVF1024,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

wiki-double-common:
    faiss:
      docker-tag: neurips23-filter-faiss
      module: neurips23.filter.faiss.faiss
      constructor: FAISS
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"indexkey": "IVF131072,SQ8", 
              "binarysig": true, 
              "threads": 16
            }]
          query-args: |
            [{"nprobe": 1, "mt_threshold":0.0003}, 
             {"nprobe": 4, "mt_threshold":0.0003}, 
             {"nprobe": 16, "mt_threshold":0.0003}, 
             {"nprobe": 32, "mt_threshold":0.0003}, 
             {"nprobe": 64, "mt_threshold":0.0003}, 
             {"nprobe": 96, "mt_threshold":0.0003}, 
             {"nprobe": 1, "mt_threshold":0.0001}, 
             {"nprobe": 4, "mt_threshold":0.0001}, 
             {"nprobe": 16, "mt_threshold":0.0001}, 
             {"nprobe": 32, "mt_threshold":0.0001}, 
             {"nprobe": 64, "mt_threshold":0.0001}, 
             {"nprobe": 96, "mt_threshold":0.0001}, 
             {"nprobe": 1, "mt_threshold":0.01}, 
             {"nprobe": 4, "mt_threshold":0.01}, 
             {"nprobe": 16, "mt_threshold":0.01}, 
             {"nprobe": 32, "mt_threshold":0.01}, 
             {"nprobe": 64, "mt_threshold":0.01}, 
             {"nprobe": 96, "mt_threshold":0.01}
            ]

